# Generated by Django 5.0.6 on 2024-05-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="rating",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="menu1",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="menu2",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
