# Generated by Django 5.0.6 on 2024-05-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0002_remove_restaurant_rating_restaurant_menu1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="service",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
