# Generated by Django 5.0.6 on 2024-06-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_resimage_restaurant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resimage",
            name="image_en_url",
        ),
        migrations.RemoveField(
            model_name="resimage",
            name="image_ja_url",
        ),
        migrations.RemoveField(
            model_name="resimage",
            name="image_ko_url",
        ),
        migrations.RemoveField(
            model_name="resimage",
            name="image_zh_url",
        ),
        migrations.AddField(
            model_name="resimage",
            name="image_en",
            field=models.ImageField(blank=True, null=True, upload_to="images/en/"),
        ),
        migrations.AddField(
            model_name="resimage",
            name="image_ja",
            field=models.ImageField(blank=True, null=True, upload_to="images/ja/"),
        ),
        migrations.AddField(
            model_name="resimage",
            name="image_ko",
            field=models.ImageField(blank=True, null=True, upload_to="images/ko/"),
        ),
        migrations.AddField(
            model_name="resimage",
            name="image_zh",
            field=models.ImageField(blank=True, null=True, upload_to="images/zh/"),
        ),
    ]
