# Generated by Django 5.0.6 on 2024-06-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0004_bookmarkrestaurantinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="mood",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
